# Generated by Django 6.1.1 on 2026-10-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_platformbankdetails_is_crypto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usdt_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço da Wallet USDT'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usdt_channel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Canal USDT (Ex: TRC20)'),
        ),
        migrations.AddField(
            model_name='platformbankdetails',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo para Depósito'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='IBAN',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Titular'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Banco'),
        ),
    ]
