# Generated by Django 6.1.1 on 2026-10-04 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser_usdt_address_customuser_usdt_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código do Cupom')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Recompensa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cupom Ativo')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Número máximo de vezes que este cupom pode ser utilizado. Deixe vazio para permitir utilizações ilimitadas.', null=True, verbose_name='Limite de Utilizações')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Utilizações')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='roulette',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='roulette',
            name='prize',
        ),
        migrations.RemoveField(
            model_name='roulette',
            name='spin_date',
        ),
        migrations.RemoveField(
            model_name='roulettesettings',
            name='prizes',
        ),
        migrations.AddField(
            model_name='roulette',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do Giro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roulette',
            name='prize_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Prêmio Ganho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roulettesettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Roleta Ativa'),
        ),
        migrations.AddField(
            model_name='roulettesettings',
            name='spin_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Custo por Giro'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Recompensa Recebida')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Resgate')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.coupon', verbose_name='Cupom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resgate de Cupom',
                'verbose_name_plural': 'Resgates de Cupons',
                'ordering': ['-redeemed_at'],
                'constraints': [models.UniqueConstraint(fields=('coupon', 'user'), name='unique_coupon_user')],
            },
        ),
    ]
